// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var queryParams;
    return queryParams = {
      parse: function(q) {
        var b, d, e, k, ma, r, s, sk, v;
        r = {};
        d = function(v) {
          return decodeURIComponent(v).replace(/\+/g, " ");
        };
        s = /([^&;=]+)=?([^&;]*)/g;
        q = d(q);
        ma = function(v) {
          var cv;
          if (typeof v !== "object") {
            cv = v;
            v = {};
            v.length = 0;
            if (cv) {
              Array.prototype.push.call(v, cv);
            }
          }
          return v;
        };
        while ((e = s.exec(q))) {
          b = e[1].indexOf("[");
          v = d(e[2]);
          if (b < 0) {
            k = d(e[1]);
            if (r[k]) {
              r[k] = ma(r[k]);
              Array.prototype.push.call(r[k], v);
            } else {
              r[k] = v;
            }
          } else {
            k = d(e[1].slice(0, b));
            sk = d(e[1].slice(b + 1, e[1].indexOf("]", b)));
            r[k] = ma(r[k]);
            if (sk) {
              r[k][sk] = v;
            } else {
              Array.prototype.push.call(r[k], v);
            }
          }
        }
        return r;
      },
      encode: function(data) {
        var d;
        d = Object.keys(data).map(function(k) {
          return encodeURIComponent(k) + '=' + encodeURIComponent(data[k]);
        });
        return d.join('&');
      }
    };
  });

}).call(this);

//# sourceMappingURL=queryparams.map
